name: Audit
env:
  MSRV: 1.66.1
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  merge_group:
    types: [checks_requested]

jobs:
  audit:
    needs: [cargo-deny] # security-audit,
    runs-on: ubuntu-latest
    if: always()
    steps:
      - run: jq --exit-status 'all(.result == "success")' <<< '${{ toJson(needs) }}'
      - name: Done
        run: exit 0
  cargo-deny:
    name: Cargo Deny
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans
          - licenses
          - sources
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          rust-version: ${{ env.MSRV }}
          command: check ${{ matrix.checks }} -s
          arguments: --all-features
          log-level: warn
